title: NegIKK
markdown: kramdown

# Подключаем свежую версию из репозитория
remote_theme: jekyll/minima

# Выбираем скин (dark или auto для подстройки под систему)
minima:
  skin: dark 

# Добавляем необходимый плагин
plugins:
  - jekyll-remote-theme
  - jekyll-feed
